before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "export DISPLAY=:99.0"
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd api; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../cmd; set_gemfile; bundle install --quiet; bundle exec cucumber features"
  - "cd ../core; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../dash; set_gemfile; bundle install --quiet; bundle exec rspec spec"
  - "cd ../promo; set_gemfile; bundle install --quiet; bundle exec rspec spec"

notifications:
  email:
    - ryan@spreecommerce.com
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#spree"
branches:
  only:
    - 1-0-stable
    - auth-take-two
    - master
rvm:
  - 1.8.7
  - 1.9.3
