before_script:
  - "ruby --version"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake"
notifications:
  email: false
  irc: "irc.freenode.org#spree"
branches:
  only:
    - 0-70-stable
