env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
script:
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd api; set_gemfile; bundle install --quiet; bundle exec rake test_app; bundle exec rspec spec"

notifications:
  email:
    - ryan@spreecommerce.com
branches:
  only:
    - api
rvm:
  - 1.8.7
  - 1.9.3
