sudo: required
dist: trusty

language: ruby

cache:
  bundler: true

env:
  - GEM=api DB=mysql
  - GEM=api DB=postgres
  - GEM=backend DB=mysql
  - GEM=backend DB=postgres
  - GEM=core DB=mysql
  - GEM=core DB=postgres
  - GEM=frontend DB=mysql
  - GEM=frontend DB=postgres
  - GEM=sample DB=mysql
  - GEM=sample DB=postgres

before_install:
  - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  - phantomjs -v
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.4.2
  - 2.3.4
  - 2.2.7
