sudo: required
dist: trusty

language: ruby

cache:
  bundler: true
  
addons:
  chrome: stable

# Commented out the failing mysql tests, these need uncommenting and the issues looking into.
env:
  - GEM=api DB=mysql
  - GEM=api DB=postgres
  # - GEM=backend DB=mysql
  - GEM=backend DB=postgres
  # - GEM=core DB=mysql
  - GEM=core DB=postgres
  - GEM=frontend DB=mysql
  - GEM=frontend DB=postgres
  - GEM=sample DB=mysql
  - GEM=sample DB=postgres

before_install:
  - sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  - phantomjs -v
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
  - mysql -u root -e "GRANT ALL ON *.* TO 'travis'@'%';"
  - wget -N https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.4.2
  - 2.3.4
  - 2.2.7